[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
constant_product_amm = "7Hr5ygzGZYj3oaQBX6SQtacuGzXJfctv6R94FkXKStSx"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
