[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
constant_product_amm = "9arTu5r1q2hAoNveV1hznrmBsaLBuvRneG7tqEygXaCT"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
